### ISSUE TITLE
Создать страницы создания и редактирования человека

### ISSUE THREAD

**Issue by reznikovkg** [reznikovkg/pedigree#28]
Добавить пустые страницы с маршрутами:

1. `/create` - CreatePersonPage
2. `/person/:id/edit` - EditPersonPage

Пока что с пустым содержанием.
Разместить в каталоге проекта /components/pages

Для 2 должен вычисляться объект человека по параметру id, как в задаче #9

**Comment by liannl** [comment]
1. Подскажите, нужно ли в страницы CreatePersonPage и EditPersonPage добавлять PageLayout?
2. В файле routes.ts регистер присваиваемой строки имеет значение? ```EDITPERSON = "EditPersonPage"```

**Comment by reznikovkg** [comment]
> Подскажите, нужно ли в страницы CreatePersonPage и EditPersonPage добавлять PageLayout?

Да

**Comment by reznikovkg** [comment]
Завершено
