### ISSUE TITLE
Связать страницу настроек

### ISSUE THREAD

**Issue by reznikovkg** [reznikovkg/pedigree#54]
Связать страницу настроек #29 с модулем хранилища #13

Изменение переключателя влияет на изменение в хранилище.

**Comment by sabudilovskiy** [comment]
Берём в работу(Будиловский, Смирнов)

**Comment by reznikovkg** [comment]
@sabudilovskiy Что? Поправляйте!

**Comment by reznikovkg** [comment]
Завершено
