### ISSUE TITLE
Создать компонент простой кнопки и панель управления

### ISSUE THREAD

**Issue by reznikovkg** [reznikovkg/pedigree#7]
Требуется создать компонент кнопки и компонент панели

Название компонента кнопки: SimpleButton

Разместить в каталоге проекта /components/ui

Компонент получает:
- slot (слот компонента)
- type (тип кнопки, от которой зависит цвет - info, warning, danger, primary)

Название компонента панели: NavigationPanel
Просто содержит 4 кнопки размещенные через flex.

<img width="850" alt="image" src="https://github.com/reznikovkg/pedigree/assets/36205504/42b75f51-69d7-4f91-87e0-9bcdbfbf98d5">

**Comment by Santiago-nve** [comment]
Здравствуйте,  меня зовут Сантьяго нве бибанг ннама,  я вязал эту тему

**Comment by reznikovkg** [comment]
> Здравствуйте, меня зовут Сантьяго нве бибанг ннама, я вязал эту тему

@Santiago-nve Здравствуйте, записал

**Comment by reznikovkg** [comment]
Завершено с ошибками
