### ISSUE TITLE
Подсказки для инпутов

### ISSUE THREAD

**Issue by reznikovkg** [reznikovkg/pedigree#89]
Для некоторых полей понадобится заготовленный список подсказок.

Использовать для поповера #10 

Обернуть для примера в форме образования инпут.
При наведении всплывают поля подсказок. 
Создать компонент InputHelper. В качестве пропс получает список строк. Строки выводятся друг под другом. При клике срабатывает emit и присваивает новое значение в обернутый инпут.

<img width="683" alt="image" src="https://github.com/reznikovkg/pedigree/assets/36205504/4c2c390e-4125-454c-ae36-3ed38c945989">

**Comment by teplinskikh** [comment]
Исправили

![image](https://github.com/reznikovkg/pedigree/assets/129896044/eeabf9f5-fc48-461b-ac5f-82badff0a064)

**Comment by reznikovkg** [comment]
Завершено
